/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.mydogtom.talaiot

import com.cdsap.talaiot.plugin.influxdb.InfluxdbExtension
import org.gradle.api.Project
import org.gradle.api.Plugin

/**
 * A simple 'hello world' plugin.
 */
class TalaiotCustomPluginPlugin: Plugin<Project> {
    override fun apply(project: Project) {

        configureTalaiot(project)

        // Register a task
        project.tasks.register("greeting") { task ->
            task.doLast {
                println("Hello from plugin 'com.github.mydogtom.talaiot.greeting'")
            }
        }
    }

    private fun configureTalaiot(project: Project) {
        project.plugins.apply("com.cdsap.talaiot.plugin.influxdb")
        project.extensions.configure(InfluxdbExtension::class.java) { talaiotExtension ->
            talaiotExtension.metrics {
                gitMetrics = false
                customMetrics(
                    ProjectFolderMetric()
                )

                talaiotExtension.publishers {
                    influxDbPublisher {
                        dbName = "test-database"
                        url = "to-do"
                        taskMetricName = "task"
                        buildMetricName = "build"
                        publishTaskMetrics = true
                    }
                }

                talaiotExtension.filter {
                    build {
                        success = true
                        requestedTasks {
                            excludes = arrayOf("myTask")
                        }
                    }
                }

                talaiotExtension.ignoreWhen {
                    envName = "RUN_ON_CI"
                    envValue = "true"
                }
            }
        }

    }
}
